name: FormWizard
author: eineki
category: Forms
tags: [form, webui, wizard]
docs: http://liberosoftware.net/FormWizard/doc.html
demo: http://liberosoftware.net/FormWizard/Examples/index.html
current: 0.3
