name: FormWizard
author: eineki
category: Forms
tags: [form, webui, wizard]
#docs: http://liberosoftware.net/projects/mootools/formwizard/
#demo: http://liberosoftware.net/project/mootools/formwizard/
current: 0.2
